name: ESLint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["feature/**"]
  schedule:
    - cron: "20 0 * * 6"

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.11.0

      - name: Setup Node.js with pnpm
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "pnpm"

      - name: Install ESLint
        run: |
          pnpm add eslint@8.10.0
          pnpm add @microsoft/eslint-formatter-sarif@2.1.7

      - name: Run ESLint
        run: pnpx eslint . --ext .js,.jsx,.ts,.tsx --config .eslintrc.js
        continue-on-error: true
