name: GitHub Actions Version Updater

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.WORKFLOW_SECRET }}

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.5.6
        with:
          committer_username: "Mirailisc"
          committer_email: "mirailisclm@gmail.com"
          commit_message: "Commit Message"
          pull_request_title: "Pull Request Title"
          token: ${{ secrets.WORKFLOW_SECRET }}
          ignore: '["actions/checkout@v2", "actions/cache@v2"]'

      - uses: paulhatch/semantic-version@v4.0.2
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          major_regexp_flags: ""
          minor_pattern: "(MINOR)"
          minor_regexp_flags: ""
          format: "${major}.${minor}.${patch}-prerelease${increment}"
          change_path: "src/my-service"
          namespace: my-service
          bump_each_commit: false
          search_commit_body: false
          user_format_type: "csv"
